///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SEDATA.Web
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Web_AddUser recording.
    /// </summary>
    [TestModule("e6dc4398-6faa-404a-9ba6-c6cc354a4ff7", ModuleType.Recording, 1)]
    public partial class Web_AddUser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::SEDATA.SEDATARepository repository.
        /// </summary>
        public static global::SEDATA.SEDATARepository repo = global::SEDATA.SEDATARepository.Instance;

        static Web_AddUser instance = new Web_AddUser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Web_AddUser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Web_AddUser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.FirstName' at Center.", repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.FirstNameInfo, new RecordItemIndex(0));
            repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.FirstName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Mubin' with focus on 'RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.FirstName'.", repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.FirstNameInfo, new RecordItemIndex(1));
            repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.FirstName.PressKeys("Mubin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.LastName' at Center.", repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.LastNameInfo, new RecordItemIndex(2));
            repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.LastName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Kadiwala' with focus on 'RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.LastName'.", repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.LastNameInfo, new RecordItemIndex(3));
            repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Textboxes.LastName.PressKeys("Kadiwala");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.Female' at Center.", repo.RanorexVIPDatabaseTestWebApplicatio.FemaleInfo, new RecordItemIndex(4));
            repo.RanorexVIPDatabaseTestWebApplicatio.Female.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.Male' at Center.", repo.RanorexVIPDatabaseTestWebApplicatio.MaleInfo, new RecordItemIndex(5));
            repo.RanorexVIPDatabaseTestWebApplicatio.Male.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.ListItems.Category.Other' at Center.", repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Category.OtherInfo, new RecordItemIndex(6));
            repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Category.Other.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.ListItems.Category.Movie' at Center.", repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Category.MovieInfo, new RecordItemIndex(7));
            repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Category.Movie.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.ListItems.Category.Music' at Center.", repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Category.MusicInfo, new RecordItemIndex(8));
            repo.RanorexVIPDatabaseTestWebApplicatio.ListItems.Category.Music.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RanorexVIPDatabaseTestWebApplicatio.InputTagAdd' at Center.", repo.RanorexVIPDatabaseTestWebApplicatio.InputTagAddInfo, new RecordItemIndex(9));
            repo.RanorexVIPDatabaseTestWebApplicatio.InputTagAdd.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
