///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SEDATA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DragNDrop recording.
    /// </summary>
    [TestModule("188bfaa9-a288-4227-922f-14a65360916e", ModuleType.Recording, 1)]
    public partial class DragNDrop : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SEDATARepository repository.
        /// </summary>
        public static SEDATARepository repo = SEDATARepository.Instance;

        static DragNDrop instance = new DragNDrop();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DragNDrop()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DragNDrop Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("b5cefc10-1087-4cdb-9117-028544959cc1")]
        public string Gender
        {
            get { return repo.Gender; }
            set { repo.Gender = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'RxMainFrame.RxTabStandard.Textbox.LastName' at Center.", repo.RxMainFrame.RxTabStandard.Textbox.LastNameInfo, new RecordItemIndex(0));
            repo.RxMainFrame.RxTabStandard.Textbox.LastName.DoubleClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Kad' with focus on 'RxMainFrame.RxTabStandard.Textbox.LastName'.", repo.RxMainFrame.RxTabStandard.Textbox.LastNameInfo, new RecordItemIndex(1));
            repo.RxMainFrame.RxTabStandard.Textbox.LastName.PressKeys("Kad");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Mubin' with focus on 'RxMainFrame.RxTabStandard.Textbox.FirstName'.", repo.RxMainFrame.RxTabStandard.Textbox.FirstNameInfo, new RecordItemIndex(2));
            repo.RxMainFrame.RxTabStandard.Textbox.FirstName.PressKeys("Mubin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.RxTabStandard.RdbMale' at Center.", repo.RxMainFrame.RxTabStandard.RdbMaleInfo, new RecordItemIndex(3));
            repo.RxMainFrame.RxTabStandard.RdbMale.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.BtnAddPerson' at Center.", repo.RxMainFrame.BtnAddPersonInfo, new RecordItemIndex(4));
            repo.RxMainFrame.BtnAddPerson.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
