///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SEDATA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Introduction_User recording.
    /// </summary>
    [TestModule("3414e3a1-ac80-4ec5-afc0-0f1ea800a063", ModuleType.Recording, 1)]
    public partial class Introduction_User : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SEDATARepository repository.
        /// </summary>
        public static SEDATARepository repo = SEDATARepository.Instance;

        static Introduction_User instance = new Introduction_User();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Introduction_User()
        {
            locWelcome = "-1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Introduction_User Instance
        {
            get { return instance; }
        }

#region Variables

        string _locWelcome;

        /// <summary>
        /// Gets or sets the value of variable locWelcome.
        /// </summary>
        [TestVariable("bbc12434-f9cf-4590-8ccc-668b4676864f")]
        public string locWelcome
        {
            get { return _locWelcome; }
            set { _locWelcome = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.EnterYourName' at Center.", repo.RxMainFrame.EnterYourNameInfo, new RecordItemIndex(0));
            //repo.RxMainFrame.EnterYourName.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Mubin' with focus on 'RxMainFrame.EnterYourName'.", repo.RxMainFrame.EnterYourNameInfo, new RecordItemIndex(1));
            //repo.RxMainFrame.EnterYourName.PressKeys("Mubin");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Mickey' on item 'RxMainFrame.EnterYourName'.", repo.RxMainFrame.EnterYourNameInfo, new RecordItemIndex(2));
            repo.RxMainFrame.EnterYourName.Element.SetAttributeValue("Text", "Mickey");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RxMainFrame.BtnSubmitUserName' at Center.", repo.RxMainFrame.BtnSubmitUserNameInfo, new RecordItemIndex(3));
            repo.RxMainFrame.BtnSubmitUserName.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", locWelcome, new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'RxMainFrame.Intro_WelcomeMessage' and assigning its value to variable 'locWelcome'.", repo.RxMainFrame.Intro_WelcomeMessageInfo, new RecordItemIndex(5));
            locWelcome = repo.RxMainFrame.Intro_WelcomeMessage.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", locWelcome, new RecordItemIndex(6));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.RxMainFrame.Self, false, new RecordItemIndex(7));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
