///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SEDATA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SEDATARepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a52ede69-57e9-4022-8dee-ee26a697468b")]
    public partial class SEDATARepository : RepoGenBaseFolder
    {
        static SEDATARepository instance = new SEDATARepository();
        SEDATARepositoryFolders.RxMainFrameAppFolder _rxmainframe;
        SEDATARepositoryFolders.List1000AppFolder _list1000;
        SEDATARepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder _ranorexvipdatabasetestwebapplicatio;
        SEDATARepositoryFolders.GoogleAppFolder _google;
        SEDATARepositoryFolders.HowToCreateAUserRatingScorecardAppFolder _howtocreateauserratingscorecard;
        SEDATARepositoryFolders.Form1AppFolder _form1;
        SEDATARepositoryFolders.Paint3DAppFolder _paint3d;
        SEDATARepositoryFolders.StuNichollsCSSPLAYCrossBrowserAppFolder _stunichollscssplaycrossbrowser;
        SEDATARepositoryFolders.GridSampleFormAppFolder _gridsampleform;
        SEDATARepositoryFolders.FormRCTAppFolder _formrct;
        SEDATARepositoryFolders.TestAutomationForGUITestingRanoreAppFolder _testautomationforguitestingranore;

        /// <summary>
        /// Gets the singleton class instance representing the SEDATARepository element repository.
        /// </summary>
        [RepositoryFolder("a52ede69-57e9-4022-8dee-ee26a697468b")]
        public static SEDATARepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SEDATARepository() 
            : base("SEDATARepository", "/", null, 0, false, "a52ede69-57e9-4022-8dee-ee26a697468b", ".\\RepositoryImages\\SEDATARepositorya52ede69.rximgres")
        {
            _rxmainframe = new SEDATARepositoryFolders.RxMainFrameAppFolder(this);
            _list1000 = new SEDATARepositoryFolders.List1000AppFolder(this);
            _ranorexvipdatabasetestwebapplicatio = new SEDATARepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder(this);
            _google = new SEDATARepositoryFolders.GoogleAppFolder(this);
            _howtocreateauserratingscorecard = new SEDATARepositoryFolders.HowToCreateAUserRatingScorecardAppFolder(this);
            _form1 = new SEDATARepositoryFolders.Form1AppFolder(this);
            _paint3d = new SEDATARepositoryFolders.Paint3DAppFolder(this);
            _stunichollscssplaycrossbrowser = new SEDATARepositoryFolders.StuNichollsCSSPLAYCrossBrowserAppFolder(this);
            _gridsampleform = new SEDATARepositoryFolders.GridSampleFormAppFolder(this);
            _formrct = new SEDATARepositoryFolders.FormRCTAppFolder(this);
            _testautomationforguitestingranore = new SEDATARepositoryFolders.TestAutomationForGUITestingRanoreAppFolder(this);
        }

#region Variables

        string _Gender = "Male";

        /// <summary>
        /// Gets or sets the value of variable Gender.
        /// </summary>
        [TestVariable("b5cefc10-1087-4cdb-9117-028544959cc1")]
        public string Gender
        {
            get { return _Gender; }
            set { _Gender = value; }
        }

        string _Category = "";

        /// <summary>
        /// Gets or sets the value of variable Category.
        /// </summary>
        [TestVariable("a8b25b5d-33c0-45ed-bf19-5465f9b1fd9e")]
        public string Category
        {
            get { return _Category; }
            set { _Category = value; }
        }

        string _age = "";

        /// <summary>
        /// Gets or sets the value of variable age.
        /// </summary>
        [TestVariable("fe459b09-1dc1-43a8-a727-8928bf54c547")]
        public string age
        {
            get { return _age; }
            set { _age = value; }
        }

        string _Country = "Margoth";

        /// <summary>
        /// Gets or sets the value of variable Country.
        /// </summary>
        [TestVariable("c43f990b-289a-4284-af41-4c2cacc0364e")]
        public string Country
        {
            get { return _Country; }
            set { _Country = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a52ede69-57e9-4022-8dee-ee26a697468b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("1a8e0132-7246-4e00-acb0-a81227ef503c")]
        public virtual SEDATARepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("fff3418d-3f7b-4dd0-ae4c-1c04e005b31c")]
        public virtual SEDATARepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatio folder.
        /// </summary>
        [RepositoryFolder("ef49e9b3-47d2-4933-a57c-bd141f6a8e92")]
        public virtual SEDATARepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder RanorexVIPDatabaseTestWebApplicatio
        {
            get { return _ranorexvipdatabasetestwebapplicatio; }
        }

        /// <summary>
        /// The Google folder.
        /// </summary>
        [RepositoryFolder("3715a66d-e1b5-4f36-bea9-6ca708cc5ff4")]
        public virtual SEDATARepositoryFolders.GoogleAppFolder Google
        {
            get { return _google; }
        }

        /// <summary>
        /// The HowToCreateAUserRatingScorecard folder.
        /// </summary>
        [RepositoryFolder("f1472b75-0459-4333-9716-e774163fbfaf")]
        public virtual SEDATARepositoryFolders.HowToCreateAUserRatingScorecardAppFolder HowToCreateAUserRatingScorecard
        {
            get { return _howtocreateauserratingscorecard; }
        }

        /// <summary>
        /// The Form1 folder.
        /// </summary>
        [RepositoryFolder("63c2ba2f-a2a4-4b88-b40f-6c0112949ca5")]
        public virtual SEDATARepositoryFolders.Form1AppFolder Form1
        {
            get { return _form1; }
        }

        /// <summary>
        /// The Paint3D folder.
        /// </summary>
        [RepositoryFolder("06c57ddb-3c32-48ab-94b7-bea542312322")]
        public virtual SEDATARepositoryFolders.Paint3DAppFolder Paint3D
        {
            get { return _paint3d; }
        }

        /// <summary>
        /// The StuNichollsCSSPLAYCrossBrowser folder.
        /// </summary>
        [RepositoryFolder("d5bc171f-257a-4ef2-a669-b23cd5def823")]
        public virtual SEDATARepositoryFolders.StuNichollsCSSPLAYCrossBrowserAppFolder StuNichollsCSSPLAYCrossBrowser
        {
            get { return _stunichollscssplaycrossbrowser; }
        }

        /// <summary>
        /// The GridSampleForm folder.
        /// </summary>
        [RepositoryFolder("8e97e2f3-9a5c-4570-9af2-c29d270d6a37")]
        public virtual SEDATARepositoryFolders.GridSampleFormAppFolder GridSampleForm
        {
            get { return _gridsampleform; }
        }

        /// <summary>
        /// The FormRCT folder.
        /// </summary>
        [RepositoryFolder("b23a31a6-e5bc-471d-9bd6-6ececc0a2a9c")]
        public virtual SEDATARepositoryFolders.FormRCTAppFolder FormRCT
        {
            get { return _formrct; }
        }

        /// <summary>
        /// The TestAutomationForGUITestingRanore folder.
        /// </summary>
        [RepositoryFolder("519c77eb-f6ce-4295-b33d-5e434756184a")]
        public virtual SEDATARepositoryFolders.TestAutomationForGUITestingRanoreAppFolder TestAutomationForGUITestingRanore
        {
            get { return _testautomationforguitestingranore; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class SEDATARepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("1a8e0132-7246-4e00-acb0-a81227ef503c")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            SEDATARepositoryFolders.RxTabStandardFolder _rxtabstandard;
            RepoItemInfo _introductionInfo;
            RepoItemInfo _enteryournameInfo;
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _imagebasedautomationInfo;
            RepoItemInfo _intro_welcomemessageInfo;
            RepoItemInfo _testdatabaseInfo;
            RepoItemInfo _btnaddpersonInfo;
            RepoItemInfo _lblnumberofpersonsnumberInfo;
            RepoItemInfo _btndeletepersonInfo;
            RepoItemInfo _chkshowimageInfo;
            RepoItemInfo _rxbuttonexitInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "1a8e0132-7246-4e00-acb0-a81227ef503c", "")
            {
                _rxtabstandard = new SEDATARepositoryFolders.RxTabStandardFolder(this);
                _introductionInfo = new RepoItemInfo(this, "Introduction", "?/?/tabpage[@accessiblename='Introduction']", "", 30000, null, "4fd1b687-4df6-4e77-83ef-c98e59b94859");
                _enteryournameInfo = new RepoItemInfo(this, "EnterYourName", "?/?/tabpage[@controlname='RxTabIntroduction']/?/?/text[@accessiblename='Enter your name']", "", 30000, null, "f73a4f4c-6dd4-4db1-86d4-97f73f4ce6e9");
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", ".//button[@controlname='btnSubmitUserName']", "", 30000, null, "3515476b-483e-4c0a-98e3-bc8b42c3809c");
                _imagebasedautomationInfo = new RepoItemInfo(this, "ImageBasedAutomation", "?/?/tabpage[@accessiblename='Image-based automation']", "", 30000, null, "285eaea2-18cb-4bce-8989-ae253ec521a4");
                _intro_welcomemessageInfo = new RepoItemInfo(this, "Intro_WelcomeMessage", ".//text[@controlname='lblWelcomeMessage']", "", 30000, null, "df2d20ac-e1ec-4de6-b399-169d4ce50a0a");
                _testdatabaseInfo = new RepoItemInfo(this, "TestDatabase", "?/?/tabpage[@accessiblename='Test database']", "", 30000, null, "6105acc6-f849-4d27-8a44-4378380d61b0");
                _btnaddpersonInfo = new RepoItemInfo(this, "BtnAddPerson", ".//button[@controlname='btnAddPerson']", "", 30000, null, "a0f9af79-a3a0-4d43-9418-fae61b435aed");
                _lblnumberofpersonsnumberInfo = new RepoItemInfo(this, "LblNumberOfPersonsNumber", ".//text[@controlname='lblNumberOfPersonsNumber']", "", 30000, null, "1352dc95-cdac-4946-933a-df55e7f0360f");
                _btndeletepersonInfo = new RepoItemInfo(this, "BtnDeletePerson", ".//button[@controlname='btnDeletePerson']", "", 30000, null, "249a1822-dda1-47f3-8f24-e56407cc719b");
                _chkshowimageInfo = new RepoItemInfo(this, "ChkShowImage", ".//checkbox[@controlname='chkShowImage']", "", 30000, null, "ff89e2ba-f46b-4f60-b60f-bbe67fbd23bd");
                _rxbuttonexitInfo = new RepoItemInfo(this, "RxButtonExit", "button[@controlname='RxButtonExit']", "", 30000, null, "6229548c-3b00-43f6-b3ab-45247a7304a0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1a8e0132-7246-4e00-acb0-a81227ef503c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1a8e0132-7246-4e00-acb0-a81227ef503c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Introduction item.
            /// </summary>
            [RepositoryItem("4fd1b687-4df6-4e77-83ef-c98e59b94859")]
            public virtual Ranorex.TabPage Introduction
            {
                get
                {
                    return _introductionInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Introduction item info.
            /// </summary>
            [RepositoryItemInfo("4fd1b687-4df6-4e77-83ef-c98e59b94859")]
            public virtual RepoItemInfo IntroductionInfo
            {
                get
                {
                    return _introductionInfo;
                }
            }

            /// <summary>
            /// The EnterYourName item.
            /// </summary>
            [RepositoryItem("f73a4f4c-6dd4-4db1-86d4-97f73f4ce6e9")]
            public virtual Ranorex.Text EnterYourName
            {
                get
                {
                    return _enteryournameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EnterYourName item info.
            /// </summary>
            [RepositoryItemInfo("f73a4f4c-6dd4-4db1-86d4-97f73f4ce6e9")]
            public virtual RepoItemInfo EnterYourNameInfo
            {
                get
                {
                    return _enteryournameInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("3515476b-483e-4c0a-98e3-bc8b42c3809c")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("3515476b-483e-4c0a-98e3-bc8b42c3809c")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item.
            /// </summary>
            [RepositoryItem("285eaea2-18cb-4bce-8989-ae253ec521a4")]
            public virtual Ranorex.TabPage ImageBasedAutomation
            {
                get
                {
                    return _imagebasedautomationInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ImageBasedAutomation item info.
            /// </summary>
            [RepositoryItemInfo("285eaea2-18cb-4bce-8989-ae253ec521a4")]
            public virtual RepoItemInfo ImageBasedAutomationInfo
            {
                get
                {
                    return _imagebasedautomationInfo;
                }
            }

            /// <summary>
            /// The Intro_WelcomeMessage item.
            /// </summary>
            [RepositoryItem("df2d20ac-e1ec-4de6-b399-169d4ce50a0a")]
            public virtual Ranorex.Text Intro_WelcomeMessage
            {
                get
                {
                    return _intro_welcomemessageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Intro_WelcomeMessage item info.
            /// </summary>
            [RepositoryItemInfo("df2d20ac-e1ec-4de6-b399-169d4ce50a0a")]
            public virtual RepoItemInfo Intro_WelcomeMessageInfo
            {
                get
                {
                    return _intro_welcomemessageInfo;
                }
            }

            /// <summary>
            /// The TestDatabase item.
            /// </summary>
            [RepositoryItem("6105acc6-f849-4d27-8a44-4378380d61b0")]
            public virtual Ranorex.TabPage TestDatabase
            {
                get
                {
                    return _testdatabaseInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The TestDatabase item info.
            /// </summary>
            [RepositoryItemInfo("6105acc6-f849-4d27-8a44-4378380d61b0")]
            public virtual RepoItemInfo TestDatabaseInfo
            {
                get
                {
                    return _testdatabaseInfo;
                }
            }

            /// <summary>
            /// The BtnAddPerson item.
            /// </summary>
            [RepositoryItem("a0f9af79-a3a0-4d43-9418-fae61b435aed")]
            public virtual Ranorex.Button BtnAddPerson
            {
                get
                {
                    return _btnaddpersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnAddPerson item info.
            /// </summary>
            [RepositoryItemInfo("a0f9af79-a3a0-4d43-9418-fae61b435aed")]
            public virtual RepoItemInfo BtnAddPersonInfo
            {
                get
                {
                    return _btnaddpersonInfo;
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item.
            /// </summary>
            [RepositoryItem("1352dc95-cdac-4946-933a-df55e7f0360f")]
            public virtual Ranorex.Text LblNumberOfPersonsNumber
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LblNumberOfPersonsNumber item info.
            /// </summary>
            [RepositoryItemInfo("1352dc95-cdac-4946-933a-df55e7f0360f")]
            public virtual RepoItemInfo LblNumberOfPersonsNumberInfo
            {
                get
                {
                    return _lblnumberofpersonsnumberInfo;
                }
            }

            /// <summary>
            /// The BtnDeletePerson item.
            /// </summary>
            [RepositoryItem("249a1822-dda1-47f3-8f24-e56407cc719b")]
            public virtual Ranorex.Button BtnDeletePerson
            {
                get
                {
                    return _btndeletepersonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnDeletePerson item info.
            /// </summary>
            [RepositoryItemInfo("249a1822-dda1-47f3-8f24-e56407cc719b")]
            public virtual RepoItemInfo BtnDeletePersonInfo
            {
                get
                {
                    return _btndeletepersonInfo;
                }
            }

            /// <summary>
            /// The ChkShowImage item.
            /// </summary>
            [RepositoryItem("ff89e2ba-f46b-4f60-b60f-bbe67fbd23bd")]
            public virtual Ranorex.CheckBox ChkShowImage
            {
                get
                {
                    return _chkshowimageInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The ChkShowImage item info.
            /// </summary>
            [RepositoryItemInfo("ff89e2ba-f46b-4f60-b60f-bbe67fbd23bd")]
            public virtual RepoItemInfo ChkShowImageInfo
            {
                get
                {
                    return _chkshowimageInfo;
                }
            }

            /// <summary>
            /// The RxButtonExit item.
            /// </summary>
            [RepositoryItem("6229548c-3b00-43f6-b3ab-45247a7304a0")]
            public virtual Ranorex.Button RxButtonExit
            {
                get
                {
                    return _rxbuttonexitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RxButtonExit item info.
            /// </summary>
            [RepositoryItemInfo("6229548c-3b00-43f6-b3ab-45247a7304a0")]
            public virtual RepoItemInfo RxButtonExitInfo
            {
                get
                {
                    return _rxbuttonexitInfo;
                }
            }

            /// <summary>
            /// The RxTabStandard folder.
            /// </summary>
            [RepositoryFolder("4cc8a8bb-d57c-48e0-976d-a2987779934e")]
            public virtual SEDATARepositoryFolders.RxTabStandardFolder RxTabStandard
            {
                get { return _rxtabstandard; }
            }
        }

        /// <summary>
        /// The RxTabStandardFolder folder.
        /// </summary>
        [RepositoryFolder("4cc8a8bb-d57c-48e0-976d-a2987779934e")]
        public partial class RxTabStandardFolder : RepoGenBaseFolder
        {
            SEDATARepositoryFolders.TextboxFolder _textbox;
            RepoItemInfo _openInfo;
            RepoItemInfo _rdbmaleInfo;

            /// <summary>
            /// Creates a new RxTabStandard  folder.
            /// </summary>
            public RxTabStandardFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabStandard", "?/?/tabpage[@controlname='RxTabStandard']", parentFolder, 30000, null, false, "4cc8a8bb-d57c-48e0-976d-a2987779934e", "")
            {
                _textbox = new SEDATARepositoryFolders.TextboxFolder(this);
                _openInfo = new RepoItemInfo(this, "Open", "?/?/button[@accessiblename='Open']", "", 30000, null, "aa4c9f84-ec23-4bd4-b3d0-b1097c12c45e");
                _rdbmaleInfo = new RepoItemInfo(this, "RdbMale", "?/?/radiobutton[@text=$Gender]", "", 30000, null, "c2bb7237-1958-4290-9d1a-bfb169ad91c7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4cc8a8bb-d57c-48e0-976d-a2987779934e")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4cc8a8bb-d57c-48e0-976d-a2987779934e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("aa4c9f84-ec23-4bd4-b3d0-b1097c12c45e")]
            public virtual Ranorex.Button Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("aa4c9f84-ec23-4bd4-b3d0-b1097c12c45e")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The RdbMale item.
            /// </summary>
            [RepositoryItem("c2bb7237-1958-4290-9d1a-bfb169ad91c7")]
            public virtual Ranorex.RadioButton RdbMale
            {
                get
                {
                    return _rdbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RdbMale item info.
            /// </summary>
            [RepositoryItemInfo("c2bb7237-1958-4290-9d1a-bfb169ad91c7")]
            public virtual RepoItemInfo RdbMaleInfo
            {
                get
                {
                    return _rdbmaleInfo;
                }
            }

            /// <summary>
            /// The Textbox folder.
            /// </summary>
            [RepositoryFolder("bc018e8e-3ee6-4cdd-bf74-452684317c0b")]
            public virtual SEDATARepositoryFolders.TextboxFolder Textbox
            {
                get { return _textbox; }
            }
        }

        /// <summary>
        /// The TextboxFolder folder.
        /// </summary>
        [RepositoryFolder("bc018e8e-3ee6-4cdd-bf74-452684317c0b")]
        public partial class TextboxFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _ageInfo;

            /// <summary>
            /// Creates a new Textbox  folder.
            /// </summary>
            public TextboxFolder(RepoGenBaseFolder parentFolder) :
                    base("Textbox", "", parentFolder, 0, null, false, "bc018e8e-3ee6-4cdd-bf74-452684317c0b", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First name']", "", 30000, null, "f8280202-a5ed-4f1f-94bb-c133caa314f8");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last name']", "", 30000, null, "c6810757-bf25-41eb-bd31-71a581652330");
                _ageInfo = new RepoItemInfo(this, "Age", "?/?/text[@controlname='upDownEdit']", "", 30000, null, "d3561989-3190-4dc2-90cc-8edb15e454b7");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bc018e8e-3ee6-4cdd-bf74-452684317c0b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("f8280202-a5ed-4f1f-94bb-c133caa314f8")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("f8280202-a5ed-4f1f-94bb-c133caa314f8")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("c6810757-bf25-41eb-bd31-71a581652330")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("c6810757-bf25-41eb-bd31-71a581652330")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Age item.
            /// </summary>
            [RepositoryItem("d3561989-3190-4dc2-90cc-8edb15e454b7")]
            public virtual Ranorex.Text Age
            {
                get
                {
                    return _ageInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Age item info.
            /// </summary>
            [RepositoryItemInfo("d3561989-3190-4dc2-90cc-8edb15e454b7")]
            public virtual RepoItemInfo AgeInfo
            {
                get
                {
                    return _ageInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("fff3418d-3f7b-4dd0-ae4c-1c04e005b31c")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _testingInfo;
            RepoItemInfo _supportInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "fff3418d-3f7b-4dd0-ae4c-1c04e005b31c", "")
            {
                _testingInfo = new RepoItemInfo(this, "Testing", "listitem[@text=$Category]", "", 30000, null, "04a8e0d0-d13b-4238-a34c-db9357ac52e6");
                _supportInfo = new RepoItemInfo(this, "Support", "listitem[@index=$age]", "", 30000, null, "46630b3e-6c4a-434e-9097-8ba4918493b0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fff3418d-3f7b-4dd0-ae4c-1c04e005b31c")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fff3418d-3f7b-4dd0-ae4c-1c04e005b31c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Testing item.
            /// </summary>
            [RepositoryItem("04a8e0d0-d13b-4238-a34c-db9357ac52e6")]
            public virtual Ranorex.ListItem Testing
            {
                get
                {
                    return _testingInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Testing item info.
            /// </summary>
            [RepositoryItemInfo("04a8e0d0-d13b-4238-a34c-db9357ac52e6")]
            public virtual RepoItemInfo TestingInfo
            {
                get
                {
                    return _testingInfo;
                }
            }

            /// <summary>
            /// The Support item.
            /// </summary>
            [RepositoryItem("46630b3e-6c4a-434e-9097-8ba4918493b0")]
            public virtual Ranorex.ListItem Support
            {
                get
                {
                    return _supportInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Support item info.
            /// </summary>
            [RepositoryItemInfo("46630b3e-6c4a-434e-9097-8ba4918493b0")]
            public virtual RepoItemInfo SupportInfo
            {
                get
                {
                    return _supportInfo;
                }
            }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatioAppFolder folder.
        /// </summary>
        [RepositoryFolder("ef49e9b3-47d2-4933-a57c-bd141f6a8e92")]
        public partial class RanorexVIPDatabaseTestWebApplicatioAppFolder : RepoGenBaseFolder
        {
            SEDATARepositoryFolders.ListItemsFolder _listitems;
            RepoItemInfo _maleInfo;
            RepoItemInfo _femaleInfo;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _countInfo;
            RepoItemInfo _clearInfo;
            RepoItemInfo _downloadfreetrialInfo;

            /// <summary>
            /// Creates a new RanorexVIPDatabaseTestWebApplicatio  folder.
            /// </summary>
            public RanorexVIPDatabaseTestWebApplicatioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexVIPDatabaseTestWebApplicatio", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "ef49e9b3-47d2-4933-a57c-bd141f6a8e92", "")
            {
                _listitems = new SEDATARepositoryFolders.ListItemsFolder(this);
                _maleInfo = new RepoItemInfo(this, "Male", ".//td[#'gender']/table//input[@name='Gender' and @type='radio' and @value='male']", "", 30000, null, "2b26014c-a5bb-40ca-9ebc-8a69230bb624");
                _femaleInfo = new RepoItemInfo(this, "Female", ".//td[#'gender']/table//input[@id='Gender']", "", 30000, null, "58478543-69aa-4b66-82f5-32ffce359d6e");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", "", 30000, null, "f63d5f51-c819-4fc0-9c01-f15679a41806");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", "", 30000, null, "d8130a20-9a87-46db-95cb-58cf3502ffe3");
                _clearInfo = new RepoItemInfo(this, "Clear", ".//input[#'Clear']", "", 30000, null, "9a0569c7-4c45-4098-bd45-be9ae96bd2d9");
                _downloadfreetrialInfo = new RepoItemInfo(this, "DownloadFreeTrial", ".//div[#'et_builder_outer_content']/div/div[1]//a[@innertext='Download free trial']", "", 30000, null, "6fbe36c0-578a-40f4-b5e5-e0df3893d561");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ef49e9b3-47d2-4933-a57c-bd141f6a8e92")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ef49e9b3-47d2-4933-a57c-bd141f6a8e92")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Male item.
            /// </summary>
            [RepositoryItem("2b26014c-a5bb-40ca-9ebc-8a69230bb624")]
            public virtual Ranorex.InputTag Male
            {
                get
                {
                    return _maleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Male item info.
            /// </summary>
            [RepositoryItemInfo("2b26014c-a5bb-40ca-9ebc-8a69230bb624")]
            public virtual RepoItemInfo MaleInfo
            {
                get
                {
                    return _maleInfo;
                }
            }

            /// <summary>
            /// The Female item.
            /// </summary>
            [RepositoryItem("58478543-69aa-4b66-82f5-32ffce359d6e")]
            public virtual Ranorex.InputTag Female
            {
                get
                {
                    return _femaleInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Female item info.
            /// </summary>
            [RepositoryItemInfo("58478543-69aa-4b66-82f5-32ffce359d6e")]
            public virtual RepoItemInfo FemaleInfo
            {
                get
                {
                    return _femaleInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("f63d5f51-c819-4fc0-9c01-f15679a41806")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("f63d5f51-c819-4fc0-9c01-f15679a41806")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("d8130a20-9a87-46db-95cb-58cf3502ffe3")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("d8130a20-9a87-46db-95cb-58cf3502ffe3")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }

            /// <summary>
            /// The Clear item.
            /// </summary>
            [RepositoryItem("9a0569c7-4c45-4098-bd45-be9ae96bd2d9")]
            public virtual Ranorex.InputTag Clear
            {
                get
                {
                    return _clearInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Clear item info.
            /// </summary>
            [RepositoryItemInfo("9a0569c7-4c45-4098-bd45-be9ae96bd2d9")]
            public virtual RepoItemInfo ClearInfo
            {
                get
                {
                    return _clearInfo;
                }
            }

            /// <summary>
            /// The DownloadFreeTrial item.
            /// </summary>
            [RepositoryItem("6fbe36c0-578a-40f4-b5e5-e0df3893d561")]
            public virtual Ranorex.ATag DownloadFreeTrial
            {
                get
                {
                    return _downloadfreetrialInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The DownloadFreeTrial item info.
            /// </summary>
            [RepositoryItemInfo("6fbe36c0-578a-40f4-b5e5-e0df3893d561")]
            public virtual RepoItemInfo DownloadFreeTrialInfo
            {
                get
                {
                    return _downloadfreetrialInfo;
                }
            }

            /// <summary>
            /// The ListItems folder.
            /// </summary>
            [RepositoryFolder("c99b9e67-bd5d-4c28-8896-071e62be9255")]
            public virtual SEDATARepositoryFolders.ListItemsFolder ListItems
            {
                get { return _listitems; }
            }
        }

        /// <summary>
        /// The ListItemsFolder folder.
        /// </summary>
        [RepositoryFolder("c99b9e67-bd5d-4c28-8896-071e62be9255")]
        public partial class ListItemsFolder : RepoGenBaseFolder
        {
            SEDATARepositoryFolders.CategoryFolder _category;
            SEDATARepositoryFolders.TextboxesFolder _textboxes;

            /// <summary>
            /// Creates a new ListItems  folder.
            /// </summary>
            public ListItemsFolder(RepoGenBaseFolder parentFolder) :
                    base("ListItems", "", parentFolder, 0, null, false, "c99b9e67-bd5d-4c28-8896-071e62be9255", "")
            {
                _category = new SEDATARepositoryFolders.CategoryFolder(this);
                _textboxes = new SEDATARepositoryFolders.TextboxesFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c99b9e67-bd5d-4c28-8896-071e62be9255")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Category folder.
            /// </summary>
            [RepositoryFolder("06cd75f9-8068-41d2-9232-fa9659bf11da")]
            public virtual SEDATARepositoryFolders.CategoryFolder Category
            {
                get { return _category; }
            }

            /// <summary>
            /// The Textboxes folder.
            /// </summary>
            [RepositoryFolder("07ba8fda-a6e9-4c4d-a5cb-7bcf66e9270d")]
            public virtual SEDATARepositoryFolders.TextboxesFolder Textboxes
            {
                get { return _textboxes; }
            }
        }

        /// <summary>
        /// The CategoryFolder folder.
        /// </summary>
        [RepositoryFolder("06cd75f9-8068-41d2-9232-fa9659bf11da")]
        public partial class CategoryFolder : RepoGenBaseFolder
        {
            RepoItemInfo _otherInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _musicInfo;

            /// <summary>
            /// Creates a new Category  folder.
            /// </summary>
            public CategoryFolder(RepoGenBaseFolder parentFolder) :
                    base("Category", ".//select[#'Category']", parentFolder, 30000, null, false, "06cd75f9-8068-41d2-9232-fa9659bf11da", "")
            {
                _otherInfo = new RepoItemInfo(this, "Other", "option[@value='Other']", "", 30000, null, "a5d6c431-27f7-43b8-9f32-19f07e6e7433");
                _movieInfo = new RepoItemInfo(this, "Movie", "option[@value='Movie']", "", 30000, null, "e98e177c-90d7-43ea-92f3-40bd3ecf81c8");
                _musicInfo = new RepoItemInfo(this, "Music", "option[@value='Music']", "", 30000, null, "c07de4cf-8ce5-49bc-86e0-f87318a271b8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("06cd75f9-8068-41d2-9232-fa9659bf11da")]
            public virtual Ranorex.SelectTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("06cd75f9-8068-41d2-9232-fa9659bf11da")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Other item.
            /// </summary>
            [RepositoryItem("a5d6c431-27f7-43b8-9f32-19f07e6e7433")]
            public virtual Ranorex.OptionTag Other
            {
                get
                {
                    return _otherInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Other item info.
            /// </summary>
            [RepositoryItemInfo("a5d6c431-27f7-43b8-9f32-19f07e6e7433")]
            public virtual RepoItemInfo OtherInfo
            {
                get
                {
                    return _otherInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("e98e177c-90d7-43ea-92f3-40bd3ecf81c8")]
            public virtual Ranorex.OptionTag Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("e98e177c-90d7-43ea-92f3-40bd3ecf81c8")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("c07de4cf-8ce5-49bc-86e0-f87318a271b8")]
            public virtual Ranorex.OptionTag Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("c07de4cf-8ce5-49bc-86e0-f87318a271b8")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }
        }

        /// <summary>
        /// The TextboxesFolder folder.
        /// </summary>
        [RepositoryFolder("07ba8fda-a6e9-4c4d-a5cb-7bcf66e9270d")]
        public partial class TextboxesFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _firstnameInfo;

            /// <summary>
            /// Creates a new Textboxes  folder.
            /// </summary>
            public TextboxesFolder(RepoGenBaseFolder parentFolder) :
                    base("Textboxes", "", parentFolder, 0, null, false, "07ba8fda-a6e9-4c4d-a5cb-7bcf66e9270d", "")
            {
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", "", 30000, null, "4b101d13-39de-40bc-9cfa-2c81fb2cbfd9");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", "", 30000, null, "30bd1b40-8b68-42c6-abb4-2d4e8523fbce");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("07ba8fda-a6e9-4c4d-a5cb-7bcf66e9270d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("4b101d13-39de-40bc-9cfa-2c81fb2cbfd9")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("4b101d13-39de-40bc-9cfa-2c81fb2cbfd9")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("30bd1b40-8b68-42c6-abb4-2d4e8523fbce")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("30bd1b40-8b68-42c6-abb4-2d4e8523fbce")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }
        }

        /// <summary>
        /// The GoogleAppFolder folder.
        /// </summary>
        [RepositoryFolder("3715a66d-e1b5-4f36-bea9-6ca708cc5ff4")]
        public partial class GoogleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _googleInfo;
            RepoItemInfo _lld4mels8ojo3j99yr19zbInfo;

            /// <summary>
            /// Creates a new Google  folder.
            /// </summary>
            public GoogleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Google", "/dom[@domain='www.google.com']", parentFolder, 30000, null, false, "3715a66d-e1b5-4f36-bea9-6ca708cc5ff4", "")
            {
                _googleInfo = new RepoItemInfo(this, "Google", "body/div[1]//img[@alt='Google']", "", 30000, null, "fded3522-e3f2-4c9d-8e98-128fb043bbc9");
                _lld4mels8ojo3j99yr19zbInfo = new RepoItemInfo(this, "LLD4meLS8OJO3j99Yr19Zb", "body/div[1]/div[2]", "", 30000, null, "d52ba8b5-72ad-4124-9da9-2155e7d530cc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3715a66d-e1b5-4f36-bea9-6ca708cc5ff4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3715a66d-e1b5-4f36-bea9-6ca708cc5ff4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Google item.
            /// </summary>
            [RepositoryItem("fded3522-e3f2-4c9d-8e98-128fb043bbc9")]
            public virtual Ranorex.ImgTag Google
            {
                get
                {
                    return _googleInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Google item info.
            /// </summary>
            [RepositoryItemInfo("fded3522-e3f2-4c9d-8e98-128fb043bbc9")]
            public virtual RepoItemInfo GoogleInfo
            {
                get
                {
                    return _googleInfo;
                }
            }

            /// <summary>
            /// The LLD4meLS8OJO3j99Yr19Zb item.
            /// </summary>
            [RepositoryItem("d52ba8b5-72ad-4124-9da9-2155e7d530cc")]
            public virtual Ranorex.DivTag LLD4meLS8OJO3j99Yr19Zb
            {
                get
                {
                    return _lld4mels8ojo3j99yr19zbInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The LLD4meLS8OJO3j99Yr19Zb item info.
            /// </summary>
            [RepositoryItemInfo("d52ba8b5-72ad-4124-9da9-2155e7d530cc")]
            public virtual RepoItemInfo LLD4meLS8OJO3j99Yr19ZbInfo
            {
                get
                {
                    return _lld4mels8ojo3j99yr19zbInfo;
                }
            }
        }

        /// <summary>
        /// The HowToCreateAUserRatingScorecardAppFolder folder.
        /// </summary>
        [RepositoryFolder("f1472b75-0459-4333-9716-e774163fbfaf")]
        public partial class HowToCreateAUserRatingScorecardAppFolder : RepoGenBaseFolder
        {
            SEDATARepositoryFolders.MainFolder _main;
            RepoItemInfo _someatagInfo;

            /// <summary>
            /// Creates a new HowToCreateAUserRatingScorecard  folder.
            /// </summary>
            public HowToCreateAUserRatingScorecardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HowToCreateAUserRatingScorecard", "/dom[@domain='www.w3schools.com']", parentFolder, 30000, null, false, "f1472b75-0459-4333-9716-e774163fbfaf", "")
            {
                _main = new SEDATARepositoryFolders.MainFolder(this);
                _someatagInfo = new RepoItemInfo(this, "SomeATag", "body/div//a", "", 30000, null, "09f95181-0f42-4fbd-ba1b-c8105af261a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f1472b75-0459-4333-9716-e774163fbfaf")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f1472b75-0459-4333-9716-e774163fbfaf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SomeATag item.
            /// </summary>
            [RepositoryItem("09f95181-0f42-4fbd-ba1b-c8105af261a1")]
            public virtual Ranorex.ATag SomeATag
            {
                get
                {
                    return _someatagInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SomeATag item info.
            /// </summary>
            [RepositoryItemInfo("09f95181-0f42-4fbd-ba1b-c8105af261a1")]
            public virtual RepoItemInfo SomeATagInfo
            {
                get
                {
                    return _someatagInfo;
                }
            }

            /// <summary>
            /// The Main folder.
            /// </summary>
            [RepositoryFolder("d38f2286-37df-45b8-bbc6-68d4184225ac")]
            public virtual SEDATARepositoryFolders.MainFolder Main
            {
                get { return _main; }
            }
        }

        /// <summary>
        /// The MainFolder folder.
        /// </summary>
        [RepositoryFolder("d38f2286-37df-45b8-bbc6-68d4184225ac")]
        public partial class MainFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextInfo;
            RepoItemInfo _turnontheoverlayeffectInfo;
            RepoItemInfo _howtouserratingInfo;
            RepoItemInfo _howtocontactchipsInfo;
            RepoItemInfo _atagpreviousInfo;

            /// <summary>
            /// Creates a new Main  folder.
            /// </summary>
            public MainFolder(RepoGenBaseFolder parentFolder) :
                    base("Main", ".//div[#'main']", parentFolder, 30000, null, false, "d38f2286-37df-45b8-bbc6-68d4184225ac", "")
            {
                _nextInfo = new RepoItemInfo(this, "Next", "?/?/a[@innertext='Next ❯']", "", 30000, null, "b4b6ae90-33c4-4596-ab80-aa08ac0c91c1");
                _turnontheoverlayeffectInfo = new RepoItemInfo(this, "TurnOnTheOverlayEffect", "button[@innertext>'Turn on the overlay effec']", "", 30000, null, "e801921a-df69-4ebe-8acc-954284787734");
                _howtouserratingInfo = new RepoItemInfo(this, "HowTOUserRating", "h1[@innertext='How TO - User Rating']", "", 30000, null, "217da1fe-9c0c-4273-8b68-1c69c4a20a85");
                _howtocontactchipsInfo = new RepoItemInfo(this, "HowTOContactChips", "h1[@innertext='How TO - Contact Chips']", "", 30000, null, "3b09f479-5917-46b0-bce7-1edccf963626");
                _atagpreviousInfo = new RepoItemInfo(this, "ATagPrevious", "?/?/a[@innertext='❮ Previous']", "", 30000, null, "1749872a-0a61-4dc4-8d8c-6dbc7374ff6e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d38f2286-37df-45b8-bbc6-68d4184225ac")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d38f2286-37df-45b8-bbc6-68d4184225ac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Next item.
            /// </summary>
            [RepositoryItem("b4b6ae90-33c4-4596-ab80-aa08ac0c91c1")]
            public virtual Ranorex.ATag Next
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Next item info.
            /// </summary>
            [RepositoryItemInfo("b4b6ae90-33c4-4596-ab80-aa08ac0c91c1")]
            public virtual RepoItemInfo NextInfo
            {
                get
                {
                    return _nextInfo;
                }
            }

            /// <summary>
            /// The TurnOnTheOverlayEffect item.
            /// </summary>
            [RepositoryItem("e801921a-df69-4ebe-8acc-954284787734")]
            public virtual Ranorex.ButtonTag TurnOnTheOverlayEffect
            {
                get
                {
                    return _turnontheoverlayeffectInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The TurnOnTheOverlayEffect item info.
            /// </summary>
            [RepositoryItemInfo("e801921a-df69-4ebe-8acc-954284787734")]
            public virtual RepoItemInfo TurnOnTheOverlayEffectInfo
            {
                get
                {
                    return _turnontheoverlayeffectInfo;
                }
            }

            /// <summary>
            /// The HowTOUserRating item.
            /// </summary>
            [RepositoryItem("217da1fe-9c0c-4273-8b68-1c69c4a20a85")]
            public virtual Ranorex.H1Tag HowTOUserRating
            {
                get
                {
                    return _howtouserratingInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The HowTOUserRating item info.
            /// </summary>
            [RepositoryItemInfo("217da1fe-9c0c-4273-8b68-1c69c4a20a85")]
            public virtual RepoItemInfo HowTOUserRatingInfo
            {
                get
                {
                    return _howtouserratingInfo;
                }
            }

            /// <summary>
            /// The HowTOContactChips item.
            /// </summary>
            [RepositoryItem("3b09f479-5917-46b0-bce7-1edccf963626")]
            public virtual Ranorex.H1Tag HowTOContactChips
            {
                get
                {
                    return _howtocontactchipsInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The HowTOContactChips item info.
            /// </summary>
            [RepositoryItemInfo("3b09f479-5917-46b0-bce7-1edccf963626")]
            public virtual RepoItemInfo HowTOContactChipsInfo
            {
                get
                {
                    return _howtocontactchipsInfo;
                }
            }

            /// <summary>
            /// The ATagPrevious item.
            /// </summary>
            [RepositoryItem("1749872a-0a61-4dc4-8d8c-6dbc7374ff6e")]
            public virtual Ranorex.ATag ATagPrevious
            {
                get
                {
                    return _atagpreviousInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagPrevious item info.
            /// </summary>
            [RepositoryItemInfo("1749872a-0a61-4dc4-8d8c-6dbc7374ff6e")]
            public virtual RepoItemInfo ATagPreviousInfo
            {
                get
                {
                    return _atagpreviousInfo;
                }
            }
        }

        /// <summary>
        /// The Form1AppFolder folder.
        /// </summary>
        [RepositoryFolder("63c2ba2f-a2a4-4b88-b40f-6c0112949ca5")]
        public partial class Form1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;
            RepoItemInfo _btresetuiInfo;
            RepoItemInfo _closeInfo;
            RepoItemInfo _lbfinishedInfo;
            RepoItemInfo _lbprogressInfo;

            /// <summary>
            /// Creates a new Form1  folder.
            /// </summary>
            public Form1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form1", "/form[@controlname='Form1']", parentFolder, 60000, null, true, "63c2ba2f-a2a4-4b88-b40f-6c0112949ca5", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "button[@controlname='button1']", "", 30000, null, "916bc71d-a5e4-44d5-a332-09287a38258d");
                _btresetuiInfo = new RepoItemInfo(this, "BtResetUI", "button[@controlname='btResetUI']", "", 30000, null, "c933a4ff-c593-4647-8c5d-dbc0681171ff");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", "", 30000, null, "1fe4f95e-3449-441b-bc28-bb85241614e3");
                _lbfinishedInfo = new RepoItemInfo(this, "LbFinished", "text[@controlname='lbFinished']", "", 30000, null, "b5cf25da-e729-451d-8676-911320c0f161");
                _lbprogressInfo = new RepoItemInfo(this, "LbProgress", "text[@controlname='lbProgress']", "", 30000, null, "2a6d2e08-7491-4389-ab7c-fa6d1509dd59");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("63c2ba2f-a2a4-4b88-b40f-6c0112949ca5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("63c2ba2f-a2a4-4b88-b40f-6c0112949ca5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("916bc71d-a5e4-44d5-a332-09287a38258d")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("916bc71d-a5e4-44d5-a332-09287a38258d")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }

            /// <summary>
            /// The BtResetUI item.
            /// </summary>
            [RepositoryItem("c933a4ff-c593-4647-8c5d-dbc0681171ff")]
            public virtual Ranorex.Button BtResetUI
            {
                get
                {
                    return _btresetuiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtResetUI item info.
            /// </summary>
            [RepositoryItemInfo("c933a4ff-c593-4647-8c5d-dbc0681171ff")]
            public virtual RepoItemInfo BtResetUIInfo
            {
                get
                {
                    return _btresetuiInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("1fe4f95e-3449-441b-bc28-bb85241614e3")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("1fe4f95e-3449-441b-bc28-bb85241614e3")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }

            /// <summary>
            /// The LbFinished item.
            /// </summary>
            [RepositoryItem("b5cf25da-e729-451d-8676-911320c0f161")]
            public virtual Ranorex.Text LbFinished
            {
                get
                {
                    return _lbfinishedInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LbFinished item info.
            /// </summary>
            [RepositoryItemInfo("b5cf25da-e729-451d-8676-911320c0f161")]
            public virtual RepoItemInfo LbFinishedInfo
            {
                get
                {
                    return _lbfinishedInfo;
                }
            }

            /// <summary>
            /// The LbProgress item.
            /// </summary>
            [RepositoryItem("2a6d2e08-7491-4389-ab7c-fa6d1509dd59")]
            public virtual Ranorex.Text LbProgress
            {
                get
                {
                    return _lbprogressInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LbProgress item info.
            /// </summary>
            [RepositoryItemInfo("2a6d2e08-7491-4389-ab7c-fa6d1509dd59")]
            public virtual RepoItemInfo LbProgressInfo
            {
                get
                {
                    return _lbprogressInfo;
                }
            }
        }

        /// <summary>
        /// The Paint3DAppFolder folder.
        /// </summary>
        [RepositoryFolder("06c57ddb-3c32-48ab-94b7-bea542312322")]
        public partial class Paint3DAppFolder : RepoGenBaseFolder
        {
            ZoomInteractorInfoClass _zoominteractorInfo;

            /// <summary>
            /// Creates a new Paint3D  folder.
            /// </summary>
            public Paint3DAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Paint3D", "/winapp[@packagename='Microsoft.MSPaint']", parentFolder, 30000, null, true, "06c57ddb-3c32-48ab-94b7-bea542312322", "")
            {
                _zoominteractorInfo = new ZoomInteractorInfoClass(this);
            }

            /// <summary>
            /// The ZoomInteractorInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("e9b37e3c-f885-4690-8a42-857b2cf65b97")]
            public class ZoomInteractorInfoClass : RepoItemInfo
            {
                /// <summary>
                /// ZoomInteractorInfoClass class constructor.
                /// </summary>
                public ZoomInteractorInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "ZoomInteractor", "?/?/element[@automationid='ZoomInteractor']", 30000, null, "e9b37e3c-f885-4690-8a42-857b2cf65b97")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e83d0088-0a7e-41b0-8477-09b172d30838")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e83d0088-0a7e-41b0-8477-09b172d30838");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e83d0088-0a7e-41b0-8477-09b172d30838")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e83d0088-0a7e-41b0-8477-09b172d30838", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("7382aaaa-3cc3-4349-ad2b-13865af78564")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("7382aaaa-3cc3-4349-ad2b-13865af78564");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("7382aaaa-3cc3-4349-ad2b-13865af78564")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("7382aaaa-3cc3-4349-ad2b-13865af78564", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("06c57ddb-3c32-48ab-94b7-bea542312322")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("06c57ddb-3c32-48ab-94b7-bea542312322")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ZoomInteractor item.
            /// </summary>
            [RepositoryItem("e9b37e3c-f885-4690-8a42-857b2cf65b97")]
            public virtual Ranorex.Unknown ZoomInteractor
            {
                get
                {
                    return _zoominteractorInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The ZoomInteractor item info.
            /// </summary>
            [RepositoryItemInfo("e9b37e3c-f885-4690-8a42-857b2cf65b97")]
            public virtual ZoomInteractorInfoClass ZoomInteractorInfo
            {
                get
                {
                    return _zoominteractorInfo;
                }
            }
        }

        /// <summary>
        /// The StuNichollsCSSPLAYCrossBrowserAppFolder folder.
        /// </summary>
        [RepositoryFolder("d5bc171f-257a-4ef2-a669-b23cd5def823")]
        public partial class StuNichollsCSSPLAYCrossBrowserAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _february2006Info;

            /// <summary>
            /// Creates a new StuNichollsCSSPLAYCrossBrowser  folder.
            /// </summary>
            public StuNichollsCSSPLAYCrossBrowserAppFolder(RepoGenBaseFolder parentFolder) :
                    base("StuNichollsCSSPLAYCrossBrowser", "/dom[@domain='www.cssplay.co.uk']", parentFolder, 30000, null, false, "d5bc171f-257a-4ef2-a669-b23cd5def823", "")
            {
                _february2006Info = new RepoItemInfo(this, "February2006", ".//div[#'info']/?/?/ul/li[6]/ul/?/?/ul/?/?/a[@innertext='February 2006']", "", 30000, null, "984c0740-ac14-4850-b9a8-19b15c8c8a19");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d5bc171f-257a-4ef2-a669-b23cd5def823")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d5bc171f-257a-4ef2-a669-b23cd5def823")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The February2006 item.
            /// </summary>
            [RepositoryItem("984c0740-ac14-4850-b9a8-19b15c8c8a19")]
            public virtual Ranorex.ATag February2006
            {
                get
                {
                    return _february2006Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The February2006 item info.
            /// </summary>
            [RepositoryItemInfo("984c0740-ac14-4850-b9a8-19b15c8c8a19")]
            public virtual RepoItemInfo February2006Info
            {
                get
                {
                    return _february2006Info;
                }
            }
        }

        /// <summary>
        /// The GridSampleFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("8e97e2f3-9a5c-4570-9af2-c29d270d6a37")]
        public partial class GridSampleFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _celldoeInfo;
            RepoItemInfo _somecheckboxInfo;

            /// <summary>
            /// Creates a new GridSampleForm  folder.
            /// </summary>
            public GridSampleFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GridSampleForm", "/form[@automationid='GridSampleForm']", parentFolder, 30000, null, true, "8e97e2f3-9a5c-4570-9af2-c29d270d6a37", "")
            {
                _celldoeInfo = new RepoItemInfo(this, "CellDoe", "table[@automationid='NameGrid']/?/?/row/list/cell[@text=$Country]/..//checkbox", "", 30000, null, "bd482526-5522-409c-972f-d04e251b3986");
                _somecheckboxInfo = new RepoItemInfo(this, "SomeCheckBox", "table[@automationid='NameGrid']/?/?/row[@index='1']/list/?/?/checkbox", "", 30000, null, "d19eeae3-9873-4b32-b2b7-fd46d145eb6b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8e97e2f3-9a5c-4570-9af2-c29d270d6a37")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8e97e2f3-9a5c-4570-9af2-c29d270d6a37")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CellDoe item.
            /// </summary>
            [RepositoryItem("bd482526-5522-409c-972f-d04e251b3986")]
            public virtual Ranorex.CheckBox CellDoe
            {
                get
                {
                    return _celldoeInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The CellDoe item info.
            /// </summary>
            [RepositoryItemInfo("bd482526-5522-409c-972f-d04e251b3986")]
            public virtual RepoItemInfo CellDoeInfo
            {
                get
                {
                    return _celldoeInfo;
                }
            }

            /// <summary>
            /// The SomeCheckBox item.
            /// </summary>
            [RepositoryItem("d19eeae3-9873-4b32-b2b7-fd46d145eb6b")]
            public virtual Ranorex.CheckBox SomeCheckBox
            {
                get
                {
                    return _somecheckboxInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The SomeCheckBox item info.
            /// </summary>
            [RepositoryItemInfo("d19eeae3-9873-4b32-b2b7-fd46d145eb6b")]
            public virtual RepoItemInfo SomeCheckBoxInfo
            {
                get
                {
                    return _somecheckboxInfo;
                }
            }
        }

        /// <summary>
        /// The FormRCTAppFolder folder.
        /// </summary>
        [RepositoryFolder("b23a31a6-e5bc-471d-9bd6-6ececc0a2a9c")]
        public partial class FormRCTAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _systemitemnamedisplayInfo;

            /// <summary>
            /// Creates a new FormRCT  folder.
            /// </summary>
            public FormRCTAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormRCT", "/form[@title='RCT']", parentFolder, 30000, null, true, "b23a31a6-e5bc-471d-9bd6-6ececc0a2a9c", "")
            {
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='ShellTabWindowClass']//element[@instance='1']//listitem[@automationid='5']/text[@automationid='System.ItemNameDisplay']", "", 30000, null, "77652ca1-2f99-49b6-8490-8f6d8f2e7c6a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b23a31a6-e5bc-471d-9bd6-6ececc0a2a9c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b23a31a6-e5bc-471d-9bd6-6ececc0a2a9c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("77652ca1-2f99-49b6-8490-8f6d8f2e7c6a")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("77652ca1-2f99-49b6-8490-8f6d8f2e7c6a")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }
        }

        /// <summary>
        /// The TestAutomationForGUITestingRanoreAppFolder folder.
        /// </summary>
        [RepositoryFolder("519c77eb-f6ce-4295-b33d-5e434756184a")]
        public partial class TestAutomationForGUITestingRanoreAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _backInfo;

            /// <summary>
            /// Creates a new TestAutomationForGUITestingRanore  folder.
            /// </summary>
            public TestAutomationForGUITestingRanoreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TestAutomationForGUITestingRanore", "/form[@title>'Test Automation for GUI Testing']", parentFolder, 30000, null, true, "519c77eb-f6ce-4295-b33d-5e434756184a", "")
            {
                _backInfo = new RepoItemInfo(this, "Back", ".//toolbar[@class='ToolbarWindow32']/button[@text='Back']", "", 30000, null, "a6eef3a4-1678-4830-81b4-5271f8ed52aa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("519c77eb-f6ce-4295-b33d-5e434756184a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("519c77eb-f6ce-4295-b33d-5e434756184a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Back item.
            /// </summary>
            [RepositoryItem("a6eef3a4-1678-4830-81b4-5271f8ed52aa")]
            public virtual Ranorex.Button Back
            {
                get
                {
                    return _backInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Back item info.
            /// </summary>
            [RepositoryItemInfo("a6eef3a4-1678-4830-81b4-5271f8ed52aa")]
            public virtual RepoItemInfo BackInfo
            {
                get
                {
                    return _backInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
