///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SEDATA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SmartAction recording.
    /// </summary>
    [TestModule("5b8753e6-ecdf-47c1-bdf5-98fd5cb10e41", ModuleType.Recording, 1)]
    public partial class SmartAction : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SEDATARepository repository.
        /// </summary>
        public static SEDATARepository repo = SEDATARepository.Instance;

        static SmartAction instance = new SmartAction();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SmartAction()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SmartAction Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='How TO - User Rating') on item 'HowToCreateAUserRatingScorecard.Main.HowTOUserRating'.", repo.HowToCreateAUserRatingScorecard.Main.HowTOUserRatingInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.HowToCreateAUserRatingScorecard.Main.HowTOUserRatingInfo, "InnerText", "How TO - User Rating");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HowToCreateAUserRatingScorecard.Main.Next' at Center.", repo.HowToCreateAUserRatingScorecard.Main.NextInfo, new RecordItemIndex(1));
            repo.HowToCreateAUserRatingScorecard.Main.Next.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HowToCreateAUserRatingScorecard.Main.TurnOnTheOverlayEffect' at Center.", repo.HowToCreateAUserRatingScorecard.Main.TurnOnTheOverlayEffectInfo, new RecordItemIndex(2));
            repo.HowToCreateAUserRatingScorecard.Main.TurnOnTheOverlayEffect.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HowToCreateAUserRatingScorecard.Main.Next' at Center.", repo.HowToCreateAUserRatingScorecard.Main.NextInfo, new RecordItemIndex(3));
            //repo.HowToCreateAUserRatingScorecard.Main.Next.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'HowToCreateAUserRatingScorecard.Main.Next'.", repo.HowToCreateAUserRatingScorecard.Main.NextInfo, new RecordItemIndex(4));
            repo.HowToCreateAUserRatingScorecard.Main.Next.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='How TO - Contact Chips') on item 'HowToCreateAUserRatingScorecard.Main.HowTOContactChips'.", repo.HowToCreateAUserRatingScorecard.Main.HowTOContactChipsInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.HowToCreateAUserRatingScorecard.Main.HowTOContactChipsInfo, "InnerText", "How TO - Contact Chips");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HowToCreateAUserRatingScorecard.Main.ATagPrevious' at Center.", repo.HowToCreateAUserRatingScorecard.Main.ATagPreviousInfo, new RecordItemIndex(6));
            repo.HowToCreateAUserRatingScorecard.Main.ATagPrevious.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HowToCreateAUserRatingScorecard.SomeATag' at Center.", repo.HowToCreateAUserRatingScorecard.SomeATagInfo, new RecordItemIndex(7));
            repo.HowToCreateAUserRatingScorecard.SomeATag.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
