///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SEDATA.Pradeep
{
    public partial class Database_AddUser
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Invoke_action_BtnAddPerson(RepoItemInfo buttonInfo)
        {
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Press() on item 'buttonInfo'.", buttonInfo);
            buttonInfo.FindAdapter<Button>().Press();
        }

        public void MySetValue(RepoItemInfo textInfo)
        {
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '05' on item 'textInfo'.", textInfo);
            textInfo.FindAdapter<Text>().Element.SetAttributeValue("Text", "05");
        }

    }
}
